[FIO fromtree] apalix-imx8: up-port initial implementation
Boot test:
U-Boot 2020.04-00118-gea539ce4dc-dirty (Jul 31 2020 - 22:57:53 +0300)

CPU:   NXP i.MX8QM RevB A53 at 1200 MHz

DRAM:  4 GiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1, FSL_SDHC: 2
Loading Environment from MMC... OK
In:    serial@5a070000
Out:   serial@5a070000
Err:   serial@5a070000
Model: Toradex Apalis iMX8 QuadMax 4GB Wi-Fi / BT IT V1.0B, Serial# 06438736
switch to partitions #0, OK
-----------------------------------------

Was tested with:
imx-mkimage: imx_5.4.24_2.1.0
imx-scfw: ab182211e("Update .gitignore to ignore our built files...")
imx-atf: imx_5.4.24_2.1.0
imx-seco: 3.6.3 [1]
-----------------------------------------

USB test:
- USB flash drive connected with OTG cable (USBO1) - works
=> usb tree
USB device tree:
  1  Hub (480 Mb/s, 0mA)
  |  u-boot EHCI Host Controller
  |
  +-2  Mass Storage (480 Mb/s, 200mA)
                USB DISK 2.0     077507A9002D

  1  Hub (5 Gb/s, 0mA)
     U-Boot XHCI Host Controller

- USB flash drive connected to USB 3.0 port (USBH4) - works
=> usb tree
USB device tree:
  1  Hub (5 Gb/s, 0mA)
  |  U-Boot XHCI Host Controller
  |
  +-2  Mass Storage (480 Mb/s, 200mA)
                USB DISK 2.0     077507A9002D

- USB flash drive connected to one of 4 USB 2.0 (USBH2 and USBH3) - doesn't
  (isn't enumerated at all)
- UMS works (USBO1)
-----------------------------------------

Network test:
=> dhcp
BOOTP broadcast 1
DHCP client bound to address 192.168.88.251 (4 ms)
Using ethernet@5b040000 device
TFTP from server 192.168.88.2; our IP address is 192.168.88.251
Filename 'zImage'.
Load address: 0x80280000
Loading: ##################################################  5.3 MiB
	 20.7 MiB/s
done
Bytes transferred = 5598256 (556c30 hex)
-----------------------------------------

MMC test:
=> mmc rescan
=> mmc list
FSL_SDHC: 0 (eMMC)
FSL_SDHC: 1
FSL_SDHC: 2
-----------------------------------------

Dropped patches from toradex_imx_v2018.03_4.14.98_2.3.0_bringup as they have
come in from mainline v2020.04 or just not relevant anymore:
2773302a("apalis-imx8: initial add")
09ab034c("apalis-imx8: add Apalis iMX8 specific device tree")
3e9d6dad("apalis-imx8: fix eMMC/MMC/SD interface muxing")
55cedfc1("apalis-imx8: remove unavailable peripherals")
1125cb6b("apalis-imx8: remove PCA9557 GPIO controllers")
47b1eeb2("apalis-imx8: fix Ethernet")
8e37e076("imx8: support UART1 as console UART for Apalis iMX8")
d42b68ec("apalis-imx8: use UART1 as console UART")
2e356ef5("apalis-imx8: remove unused GPIOs")
954bef99("apalis-imx8: set device tree to Apalis DT by default")
ce9ae949("apalis-imx8: load HDMI firmware")
e90b8d36("apalis-imx8: use eMMC as environment location/default boot device")
d872cd6e("apalis-imx8: add default memory layout and network options")
ee3bf34e("tdx-cfg-block: add Apalis iMX8 QuadMax support")
cdac0b13("apalis-imx8: config: remove pcie and sata")
1e77935d("apalis-imx8.c: fix typo")
3e6440d1("apalis-imx8: forward port to 2018.03")
365994c5("apalis-imx8: adjust copyright/licensing headers")
365994c5("apalis-imx8: adjust copyright/licensing headers ")
5bd6bdb9("apalis-imx8: change top-level compatible")
3d7dde4f("apalis-imx8: clean-up device tree")
5d2d7ec2("apalis-imx8: clean-up configuration")
58354713("apalis-imx8: clean-up board file")
7af4c9cb("apalis-imx8: fused modules boot from emmc")
478ad2f0("apalis-imx8: clean-up ethernet functionality")
dfc9a6db("apalis-imx8: remove board code for usdhc")
f574377c("apalis-imx8: modify default ramdisk loading address")
186747eb("apalis-imx8: do not undef configs configured using Kconfig")
adb20873("apalis-imx8: make sure config block fdt fix-ups are called")
ff45d3d5("apalis-imx8: increase bootm loading size")
912a867e("apalis-imx8: enable distro boot in tezi")
b7beb5e5("apalis-imx8.h: move environment into first boot area")
70a89d49("apalis-imx8: add scriptaddr for distroboot")
ca562b4d("apalis-imx8: enable FDT relocation")
32948b33("apalis-imx8: fix ramdisk relocation address")
62493440("apalis-imx8/colibri-imx8x: use proper distroboot script")
f1993901("apalis-imx8/colibri-imx8x: set fdtfile since it is used by distro bootcmd")
83ec3f91("include: apalis-imx8.h: add default tdxargs pci=nomsi")
bb64b46f("include: apalis-imx8.h: change tdxargs to defargs for pci_nomsi")
a638c2aa("include: apalis-imx8.h: change default devicetree file")
7a829fc7("configs: apalis/colibri-imx8: change bootdelay to one second")
c707a04a("ARM: dts: imx8qxp-apalis: Remove phy-reset-post-delay")
6415bc94("config: apalis/colibri-imx8*: Add fdt_high variable without value")
96c61bda("ARM: dts: apalis-imx8qm: update node fec1")
cb3eb29b("config: apalis-imx8: fix auto-negotiation timeout error")
34ecf495("apalis-imx8: Remove fdt_file env variable")
ff527ebc("apalis-imx8: Implement hardware version detection")
4653dcf8("apalis-imx8x: sync with MEK platform")
5b32f0b4("apalis-imx8: Fix hardware version detection in recovery mode")
d626574b("apalis-imx8x: usb3 bringup")

Set fdt_high to 0xffffffffffffffff in order to avoid copying fdt
during boot. It fixes allocation error [2].

Note that such solution can't be upstreamed (see [3]) so remark it as
temphack.

[1] https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/imx-seco-3.6.3.bin
[2]
...
   Loading fdt from 0x86dd0a38 to 0x83000000
   Booting using the fdt blob at 0x83000000
   Uncompressing Kernel Image
   Loading Ramdisk to fb32c000, end fb67a669 ... OK
ERROR: Failed to allocate 0x22ff9 bytes below 0xfe000000.
device tree - allocation error
FDT creation failed! hanging...### ERROR ### Please RESET the board ###
...
[3]
  https://patchwork.ozlabs.org/project/uboot/patch/20210722154943.127775-2-oleksandr.suvorov@toradex.com/#2723077

Signed-off-by: Igor Opaniuk <igor.opaniuk@toradex.com>
Co-developed-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>