[FIO tosquash] common: bootfirmware_info: fix building warnings
Fix using an undeclared function and miscasting of a const variable [1].

[1]
common/bootfirmware_info.c: In function ‘get_boot_firmware_info’:
common/bootfirmware_info.c:27:17: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   27 |         version = fdt_getprop(gd->fdt_blob, node, "bootfirmware-version", NULL);
      |                 ^
common/bootfirmware_info.c:30:17: warning: implicit declaration of function ‘env_set’ [-Wimplicit-function-declaration]
   30 |                 env_set("dt_bootfirmware_version", version);
      |                 ^~~~~~~

Fixes: 57e13388954 ("[FIO internal] common: introduce bootfirmware info")
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>